
all : lab4-1 lab4-2 lab4-3 lab4-4 lab4-5 jonSUGER

lab4-1 : 
	gcc -Wall -o lab4-1 -lGL -lglut -ljpeg lab4-1.c helpers.c readppm.c readjpeg.c zpr.c cube.c loadobj.c
lab4-2 :
	gcc -Wall -o lab4-2 -lGL -lglut -ljpeg lab4-2.c helpers.c readppm.c readjpeg.c zpr.c cube.c loadobj.c
lab4-3 :
	gcc -Wall -o lab4-3 -lGL -lglut -ljpeg lab4-3.c helpers.c readppm.c readjpeg.c zpr.c cube.c loadobj.c
lab4-4 :
	gcc -Wall -o lab4-4 -lGL -lglut -ljpeg lab4-4.c helpers.c readppm.c readjpeg.c zpr.c cube.c loadobj.c
lab4-5 :
	gcc -Wall -o lab4-5 -lGL -lglut -ljpeg lab4-5.c helpers.c readppm.c readjpeg.c zpr.c cube.c loadobj.c
clean :
	rm lab4-1 lab4-2 lab4-3 lab4-4 lab4-5  jonsASS

