
all : lab2-1 lab2-2 lab2-3 lab2-4 lab2-6 lab2-7 lab2-8 lab2-9

lab2-1 : lab2-1.c helpers.c readppm.c readjpeg.c zpr.c cube.c loadobj.c
	gcc -Wall -o lab2-1 -lGL -lglut -ljpeg lab2-1.c helpers.c readppm.c readjpeg.c zpr.c cube.c loadobj.c


lab2-2 : lab2-2.c helpers.c readppm.c readjpeg.c zpr.c cube.c loadobj.c
	gcc -Wall -o lab2-2 -lGL -lglut -ljpeg lab2-2.c helpers.c readppm.c readjpeg.c zpr.c cube.c loadobj.c


lab2-3 : lab2-3.c helpers.c readppm.c readjpeg.c zpr.c cube.c loadobj.c
	gcc -Wall -o lab2-3 -lGL -lglut -ljpeg lab2-3.c helpers.c readppm.c readjpeg.c zpr.c cube.c loadobj.c

lab2-4 : lab2-4.c helpers.c readppm.c readjpeg.c zpr.c cube.c loadobj.c
	gcc -Wall -o lab2-4 -lGL -lglut -ljpeg lab2-4.c helpers.c readppm.c readjpeg.c zpr.c cube.c loadobj.c

lab2-6 : lab2-6.c helpers.c readppm.c readjpeg.c zpr.c cube.c loadobj.c
	gcc -Wall -o lab2-6 -lGL -lglut -ljpeg lab2-6.c helpers.c readppm.c readjpeg.c zpr.c cube.c loadobj.c


lab2-7 : lab2-7.c helpers.c readppm.c readjpeg.c zpr.c cube.c loadobj.c
	gcc -Wall -o lab2-7 -lGL -lglut -ljpeg lab2-7.c helpers.c readppm.c readjpeg.c zpr.c cube.c loadobj.c

lab2-8 : lab2-8.c helpers.c readppm.c readjpeg.c zpr.c cube.c loadobj.c
	gcc -Wall -o lab2-8 -lGL -lglut -ljpeg lab2-8.c helpers.c readppm.c readjpeg.c zpr.c cube.c loadobj.c

lab2-9 : lab2-9.c helpers.c readppm.c readjpeg.c zpr.c cube.c loadobj.c
	gcc -Wall -o lab2-9 -lGL -lglut -ljpeg lab2-9.c helpers.c readppm.c readjpeg.c zpr.c cube.c loadobj.c

clean :
	rm lab2-1 lab2-2 lab2-3 lab2-4 lab2-6 lab2-7 lab2-8 lab2-9
