
all : lab3-1 lab3-3 lab3-4 lab3-6 lab3-7 lab3-8

lab3-1 : lab3-1.c helpers.c readppm.c readjpeg.c zpr.c loadobj.c shaderutils.c
	gcc -Wall -std=c99 -o lab3-1 -lglut -lGL -ljpeg lab3-1.c helpers.c readppm.c readjpeg.c zpr.c loadobj.c shaderutils.c 

lab3-3 : lab3-3.c helpers.c readppm.c readjpeg.c zpr.c loadobj.c shaderutils.c
	gcc -Wall -std=c99 -o lab3-3 -lglut -lGL -ljpeg lab3-3.c helpers.c readppm.c readjpeg.c zpr.c loadobj.c shaderutils.c 

lab3-4 : lab3-4.c helpers.c readppm.c readjpeg.c zpr.c loadobj.c shaderutils.c
	gcc -Wall -std=c99 -o lab3-4 -lglut -lGL -ljpeg lab3-4.c helpers.c readppm.c readjpeg.c zpr.c loadobj.c shaderutils.c 

lab3-5 : lab3-5.c helpers.c readppm.c readjpeg.c zpr.c loadobj.c shaderutils.c
	gcc -Wall -std=c99 -o lab3-5 -lglut -lGL -ljpeg lab3-5.c helpers.c readppm.c readjpeg.c zpr.c loadobj.c shaderutils.c 

lab3-6 : lab3-6.c helpers.c readppm.c readjpeg.c zpr.c loadobj.c shaderutils.c
	gcc -Wall -std=c99 -o lab3-6 -lglut -lGL -ljpeg lab3-6.c helpers.c readppm.c readjpeg.c zpr.c loadobj.c shaderutils.c 

lab3-7 : lab3-7.c helpers.c readppm.c readjpeg.c zpr.c loadobj.c shaderutils.c
	gcc -Wall -std=c99 -o lab3-7 -lglut -lGL -ljpeg lab3-7.c helpers.c readppm.c readjpeg.c zpr.c loadobj.c shaderutils.c 

lab3-8 : lab3-8.c helpers.c readppm.c readjpeg.c zpr.c loadobj.c shaderutils.c
	gcc -Wall -std=c99 -o lab3-8 -lglut -lGL -ljpeg lab3-8.c helpers.c readppm.c readjpeg.c zpr.c loadobj.c shaderutils.c 

clean :
	rm lab3-1 lab3-3 lab3-4 lab3-6 lab3-7 lab3-8

